### ISSUE TITLE
Applications cannot be added to Access Package

### ISSUE THREAD

**Issue by brine0m** [ATVWGS/tenant-management-framework#15]
When adding an application to an access package, TMF will fail because it expects the resourceRole attribute to be a value of either 'Member" or "Owner"

This is correct for groups but will not work for applications. The default value for applications is User, however it is possible that it could be anything because you can setup custom roles on an application

Short term fix would be to remove the Validation set for this parameter. Longer terms would likely need to do some sort of lookup for what the valid roles are on the application and then use that as the validation set.

https://github.com/ATVWGS/tenant-management-framework/blob/73cd30df2779c6bd1956da023d59981739c8fabc/TMF/functions/entitlementManagement/accessPackageResource/Register-TmfAccessPackageResource.ps1#L16

**Comment by ATVWGS** [comment]
We are investigating what side effects this may have removing the validation set and also checking how to support applications correctly within AccessPackages.

**Comment by ATVWGS** [comment]
Hi @brine0m,

I've just released a preview version that is working with applications in accessPackages. A lookup of valid roles within the Register function can not work, because a new accessPackageResource is not yet deployed during the Register flow and therefore roles of the application cannot be gathered. The validation set was completly removed.
Here is an example how accessPackagesResources could look like:

"accessPackageResources":  [
                                       {
                                           "originSystem":  "AadApplication",
                                           "resourceRole":  "Default Access",
                                           "resourceType":  "Application",
                                           "resourceIdentifier":  "Graph Explorer"
                                       },
									   {
                                           "originSystem":  "AadGroup",
                                           "resourceRole":  "Member",
                                           "resourceIdentifier":  "Some group name"
                                       }
                                   ]

Note: The "resourceRole" attribute of the application can only be the displayname of the role.
